// <auto-generated />
using Exerc_Alunos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exerc_Alunos.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210414022421_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exerc_Alunos.Models.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("alunos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Nome = "Danilo",
                            cpf = "12345678996",
                            endereco = "rua Cesario",
                            materia = "Historia",
                            telefone = "1696546578"
                        },
                        new
                        {
                            id = 2,
                            Nome = "Luiz",
                            cpf = "32566456666",
                            endereco = "rua amador bueno",
                            materia = "Geografia",
                            telefone = "169999854"
                        },
                        new
                        {
                            id = 3,
                            Nome = "Andre",
                            cpf = "11112525664",
                            endereco = "rua luz",
                            materia = "Educação Fisica",
                            telefone = "1696546578"
                        },
                        new
                        {
                            id = 4,
                            Nome = "Luiz Careca",
                            cpf = "5556678996",
                            endereco = "rua senador",
                            materia = "Filosofia",
                            telefone = "1696546578"
                        },
                        new
                        {
                            id = 5,
                            Nome = "Daniel",
                            cpf = "02525678996",
                            endereco = "rua chile",
                            materia = "portugues",
                            telefone = "1696546578"
                        },
                        new
                        {
                            id = 6,
                            Nome = "Rafael",
                            cpf = "6666545678996",
                            endereco = "rua portugal",
                            materia = "ciencia",
                            telefone = "1696546578"
                        },
                        new
                        {
                            id = 7,
                            Nome = "Diogo",
                            cpf = "125555678996",
                            endereco = "rua Brasil",
                            materia = "portugues",
                            telefone = "1696546578"
                        },
                        new
                        {
                            id = 8,
                            Nome = "Sergio",
                            cpf = "652345678996",
                            endereco = "rua valentina",
                            materia = "geografia",
                            telefone = "1696546578"
                        },
                        new
                        {
                            id = 9,
                            Nome = "Joao",
                            cpf = "45679998996",
                            endereco = "rua cerqueira cesar",
                            materia = "matematica",
                            telefone = "1696546578"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
